### ISSUE TITLE
DocumentStore hygiene: idempotent soft delete, safe upsert (createdAt/tombstones, non-array path), Clock for lastSavedAt, no-op update

### ISSUE THREAD

**Issue by samuelya** [samuelya/SevenHabitsTools#121]
## Context
Code-quality follow-up to #34 (signals document store, merged in PR #110). Tester-34's round-1 checklist (https://github.com/samuelya/SevenHabitsTools/pull/110#issuecomment-5674659506) listed several non-blocking observations that were not filed as bugs. Each one below was re-checked against `main` at bf677c1 and is still present; the misnamed `data-error-page.spec.ts` test from the same list was already renamed in round 2 and is not included. The UX items on the data error page are in #117; the `undefined`-from-`load()` note went to #35. Owner approved filing these as one small issue.

Files: `src/web/src/app/core/data/document.store.ts`, `record.ts`, `document-persistence.ts`.

1. **`softDeleteRecord` re-tombstones.** `softDelete()` (`record.ts`) sets `deletedAt` and `updatedAt` unconditionally, so calling it on an already-tombstoned record moves the original `deletedAt` forward. With latest-wins merge (architecture §5) that can resurrect ordering decisions on another device. On a path with no collection it also creates `[]` and bumps `meta.updatedAt` although nothing was deleted.
2. **`upsertRecord` replaces the stored record wholesale.** A caller-supplied `createdAt` overwrites the original, and passing a record without `deletedAt` silently revives a tombstoned one. Both violate the record rules in §6 (`createdAt` immutable; tombstones never hard-removed).
3. **`upsertRecord` on a non-array path** throws a raw `TypeError: list.findIndex is not a function`. It should fail with a clear error, consistent with #112's guard in `update()`.
4. **`lastSavedAt` bypasses the clock.** `document-persistence.ts` sets `lastSavedAtSignal` with `new Date()`; the store stamps with the injected `Clock`. Tests with a fake clock cannot assert the value.
5. **No-op `update()` still stamps and saves.** When the updater returns the same value, `mutate()` bumps `meta.updatedAt` and the persistence effect schedules a save. Harmless for the user, but it produces spurious `updatedAt` changes that the future sync merge will treat as edits.

## User story
As the user, I want record timestamps and tombstones to stay accurate under every store operation so that a later sync or import merges my data correctly on every device.

## Acceptance criteria
- [ ] `softDeleteRecord` on an already-tombstoned record is a no-op (keeps the original `deletedAt` and `updatedAt`, does not touch `meta.updatedAt`); on a path that holds no array it throws a clear error and changes nothing
- [ ] `upsertRecord` preserves the stored `createdAt` when the record exists; an explicit decision, documented in the JSDoc, on tombstones: either it preserves `deletedAt` unless the caller passes `deletedAt: undefined` deliberately via a dedicated `restoreRecord(path, id)` method, or upserting a tombstoned id throws. Pick one, write it down, test it
- [ ] `upsertRecord` on a non-array path throws a descriptive error naming the path (same style as #112's guard), never a raw `TypeError`
- [ ] `DocumentPersistence` sets `lastSavedAt` from the injected `Clock`; the existing fake-clock tests assert the exact value
- [ ] `update()` whose updater returns a value equal (`Object.is`) to the current one leaves the document, `meta.updatedAt` and `dirty` untouched and schedules no save
- [ ] Unit tests for each item above (store spec, record spec, persistence spec); existing 129 tests stay green
- [ ] No behaviour change for callers already covered by #112, #113, #116 (their regression tests stay green)
- [ ] Usable at 360 px width and on desktop (N/A: no UI change)
- [ ] All strings in `en` and `ar` Transloco scope (N/A: no strings)
- [ ] Keyboard and screen-reader usable (N/A: no UI change)
- [ ] Data saved in the JSON document, survives reload and export/import (unchanged; no schema change)
- [ ] Unit tests for logic and components

## Data model
No schema change. Semantics of `createdAt`, `updatedAt` and `deletedAt` per architecture §6 are enforced, not changed.

## Dependencies
- #34 Signals-based in-memory store + StorageAdapter interface (closed)
- #112 Bug: `update()` through an array or primitive (closed; reuse its error style)

## Related
- #117 Data error page polish (the UX half of the same checklist)
- #45 / #37 merge logic will rely on the timestamps this issue keeps honest

## Ownership
Agent: frontend-coder — tested by tester
Size: S

**Comment by samuelya** [comment]
Owner code-review findings, non-blocking (no production caller exercises the risky paths today; one candidate — throw inside documentSignal.update() — was investigated and refuted as safe). Deferred as follow-up cleanup rather than blocking this PR:
1. `update()`'s new `Object.is` no-op guard would silently drop an edit from an updater that mutates in place and returns the same reference (currently no real caller does this, but it's a live trap).
2. `describeKind()` duplicates array/typeof naming logic already in `document-path.utils.ts`.
3. `upsertRecord` (defaults missing path to `[]`) and `softDeleteRecord` (throws on missing path) are asymmetric for the same not-yet-initialized-path case.
4. Test helper `fakeClock()` duplicates an identical inline clock stub in `document.store.spec.ts`.
5. `upsertRecord`/`softDeleteRecord` each scan their array twice (find, then map/spread) instead of once via `findIndex`.
6. `describeKind(null)` reads "a object" instead of "an object" in the thrown error message.
